# Generated by Django 3.1.5 on 2021-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='113.jpg', upload_to='avatar/%Y/%m/%d'),
        ),
    ]
