# Generated by Django 3.1.5 on 2021-01-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210117_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestionsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RatingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile', verbose_name='От')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Рейтинг вопросов',
                'verbose_name_plural': 'Рейтинги вопросов',
            },
        ),
    ]
