# Generated by Django 3.1.5 on 2021-01-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ratingquestions_ratingquestionsmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingQuestionsManager',
            new_name='RatingManager',
        ),
    ]
