# Generated by Django 3.1.5 on 2021-01-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210117_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingManager',
        ),
    ]
