# Generated by Django 3.1.5 on 2021-01-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210116_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.IntegerField(default=0, verbose_name='Число ответов'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile', verbose_name='Профиль'),
        ),
    ]
